[package]
name = "hello-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.27"
rand = "0.9"
clearscreen = "4.0.2"
colored = "2.0"    
prettytable-rs = "0.10"   
indicatif = "0.17"